font_family      commitmono nerd font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 14
window_padding_width 10
background_opacity 1
enable_audio_bell no
confirm_os_window_close 0

foreground              #cdd6f4
background              #1e1e2e
selection_foreground    #1e1e2e
selection_background    #f5e0dc

# cursor colors
cursor                  #f5e0dc
cursor_text_color       #1e1e2e

url_color               #b4befe

active_border_color     #cba6f7
inactive_border_color   #8e95b3
bell_border_color       #eba0ac

wayland_titlebar_color system

active_tab_foreground   #11111b
active_tab_background   #cba6f7
inactive_tab_foreground #cdd6f4
inactive_tab_background #181825
tab_bar_background      #11111b

mark1_foreground #1e1e2e
mark1_background #87b0f9
mark2_foreground #1e1e2e
mark2_background #cba6f7
mark3_foreground #1e1e2e
mark3_background #74c7ec

# the 16 terminal colors

# black
color0 #43465a
color8 #43465a

# red
color1 #f38ba8
color9 #f38ba8

# green
color2  #a6e3a1
color10 #a6e3a1

# yellow
color3  #f9e2af
color11 #f9e2af

# blue
color4  #87b0f9
color12 #87b0f9

# magenta
color5  #f5c2e7
color13 #f5c2e7

# cyan
color6  #94e2d5
color14 #94e2d5

# white
color7  #cdd6f4
color15 #a1a8c9
