font_family      commitmono nerd font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 14
window_padding_width 10
background_opacity 1
enable_audio_bell no
confirm_os_window_close 0

foreground              #ffffff
background              #0f0f0f
selection_foreground    #0d0d0d
selection_background    #aaaaaa

# cursor colors
cursor                  #aaaaaa
cursor_text_color       #0d0d0d

url_color               #cccccc

active_border_color     #dddddd
inactive_border_color   #666666
bell_border_color       #ffffff

wayland_titlebar_color system

active_tab_foreground   #0d0d0d
active_tab_background   #dddddd
inactive_tab_foreground #ffffff
inactive_tab_background #222222
tab_bar_background      #0d0d0d

mark1_foreground #0d0d0d
mark1_background #bbbbbb
mark2_foreground #0d0d0d
mark2_background #dddddd
mark3_foreground #0d0d0d
mark3_background #999999

# the 16 terminal colors

# black
color0 #222222
color8 #444444

# red
color1 #f38ba8
color9 #f38ba8

# green
color2  #a6e3a1
color10 #a6e3a1

# yellow
color3  #f9e2af
color11 #f9e2af

# blue
color4  #87b0f9
color12 #87b0f9

# magenta
color5  #f5c2e7
color13 #f5c2e7

# cyan
color6  #94e2d5
color14 #94e2d5

# white
color7  #ffffff
color15 #dddddd
